package:
  name: snpalign
  version: "0.0.10"

source:
  path: .

requirements:
  build:
    - python
    - ragtag
    - gsAlign
    - ezclermont
    - prokka
    - scipy

  run:
    - python
    - ragtag
    - gsAlign
    - ezclermont
    - prokka
    - scipy

test:
  imports:
    - snpalign

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  home:
